### PR TITLE
reverse merging release 1.4.1 to develop

### PR DESCRIPTION
**Pull request by mauroservienti**

### CODE REVIEW

**Comment by micdenny** [comment]
ops in develop, I think we have to leave the `-prerelease` tag before `-build` tag

image

**Comment by mauroservienti** [comment]
fixing...

On Tue, Jan 5, 2016 at 3:46 PM, Michael Denny <notifications@github.com>
wrote:

> ops in develop, I think we have to leave the -prerelease tag before -build
> tag
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1633595/12117827/6f22699c-b3c3-11e5-8bdc-a3c35f582e72.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RadicalFx/Radical.Windows.Presentation.CastleWindsor/pull/12#issuecomment-169020242>
> .
>



-- 
Mauro Servienti

**Comment by micdenny** [comment]
I think the version in develop should remain `1.4.1-alpha2+{build}`

**Comment by mauroservienti** [comment]
build green again in `develop` as well.

**Comment by micdenny** [comment]
could seems a weird behavior, but actually make sense, on MyGet only prerelease packages are in it, also other repositories are like that, they only contains prerelease packages, probably also to avoid confusion and avoid taking release version from a repo that can be thrown away.

**Comment by mauroservienti** [comment]
Fully agree

**Comment by micdenny** [comment]
@mauroservienti mmmmm...... did you removed master branch?! ahahah :smile:

**Comment by micdenny** [comment]
a little bit extreme IMHO! :smile:

**Comment by mauroservienti** [comment]
Oh, shit. I'm too used to press the `delete branch` button :smile: 
Restored :smile:

**Comment by micdenny** [comment]
I could not believe my eyes, thank god is git! :smile:

**Pull request merged**
