### PR TITLE
Release 1.4.1

### PR DESCRIPTION
**Pull request by mauroservienti**
@micdenny please review.

### CODE REVIEW

**Comment by mauroservienti** [comment]
Once merged I'll reverse merge to `develop`.

**Comment by micdenny** [comment]
please change the `deploy: name:` here: https://github.com/RadicalFx/Radical.Windows.Presentation.CastleWindsor/pull/11/files#diff-180360612c6b8c4ed830919bbb4dd459R77

changing in `NuGet public feed` as it done here: https://github.com/RadicalFx/Radical/blob/develop/appveyor.yml#L86

so it will pushed directly on official nuget repo

**Comment by mauroservienti** [comment]
done

**Comment by micdenny** [comment]
good to go!

**Pull request merged**
