### PR TITLE
Merge pull request #26 from RadicalFx/release/1.6

### PR DESCRIPTION
**Pull request by mauroservienti**
reverse merge latest release

### CODE REVIEW

**Comment by mauroservienti** [comment]
@micdenny is this really required?

**Comment by micdenny** [comment]
I think you can do it without a PR

**Comment by mauroservienti** [comment]
just tried to:
- rebase `develop` on `master`
- `push`

rejected, because of protected branches. A PR is needed, assigned you as reviewer.

**Comment by mauroservienti** [comment]
@micdenny can you approve this to get it going? thanks

**Comment by mauroservienti** [comment]
@micdenny ping 😄

**Pull request merged**
