### PR TITLE
release/1.5

### PR DESCRIPTION
**Pull request by mauroservienti**
This should trigger the release process and GitVersion should tag everything as expected

### CODE REVIEW

**Comment by micdenny** [comment]
was the version necessary `release/1.5`? or we can use only one fixed branch `release`? as far as I understand GitVersion is able to determine the correct version, I think if you merge into `release` it will use the latest calculater version that should already be `1.5.0`, then after build succeeded add tag the `1.5.0` so next push on develop will take `1.6.0` version

**Comment by mauroservienti** [comment]
that's a good point, I don't think it is necessary. I'll wait for the build to complete and see what happens, we can test what happens without using the {version} on another minor package, such as Autofac or Unity*. Or once the build is completed, I can close this PR and open another one without the version.

**Comment by mauroservienti** [comment]
merging this should push to `Nuget`, we'll see :smile:

**Comment by mauroservienti** [comment]
yeah!

image

**Pull request merged**
