### PR TITLE
Fixes icon url

### PR DESCRIPTION
**Pull request by mauroservienti**
@micdenny please review

### CODE REVIEW

**Comment by micdenny** [comment]
everything's fine, @mauroservienti can you please bump the version to a non-breaking number?

thank you!

**Comment by mauroservienti** [comment]
Questions:

1. don't you think that changing the version due to a change that is not related at all to code/features/behaviors is wrong? Just asking.
* since this is going to be merged into `master` as well should we change both versions here?
* Is there any good reason to have 2 versions: one for develop and one for master? or should it be just one?

**Comment by micdenny** [comment]
> don't you think that changing the version due to a change that is not related at all to code/features/behaviors is wrong? Just asking.

It depends, if you want the icon on nuget now, you need to (you can't overwrite on nuget, only on myget), if you want it later as probably make more sense also to me, yes in that case we should really avoid it! **so, please reset the latest commit and force the push on the same branch.** This will end-up by having the nuget packages on myget overwrited, and nothing on nuget even if we merge on master (only the artifacts on build server).

> since this is going to be merged into master as well should we change both versions here?

probably because of **1.** we should wait to merge as well having some code/features/behaviors to push

BTW to reply your question if it was a feature PR, I think we should wait to change the master version just because in myget we could have more and more alpha and beta version (let's say nightly builds), instead on nuget we can have squashed release more stable even if they are alpha or beta, but more stable for audience.

> Is there any good reason to have 2 versions: one for develop and one for master? or should it be just one?

We can choose if we need to have develop version or not, we can use the same version and build number for "nightly builds" on myget.

**Comment by mauroservienti** [comment]
Another question @micdenny: let's say that the actual develop version is 1.2.0, as a sample, if we need to bump the version number each time we open a PR to introduce 3 features in the same release we'll move from 1.2.0 to 1.2.3 even if it is a single release.

Now, if we merge something on develop without bumping the version the package version generated by the build server is always unique because it contains the build number, so we'll end up with something like 1.2.0-unstable-1234567

Once everything is merged into develop we can create a release branch where the build number is bumped to 1.2.1 and merge into master and develop.

Thoughts?

**Comment by micdenny** [comment]
> Now, if we merge something on develop without bumping the version the package version generated by the build server is always unique because it contains the build number, so we'll end up with something like 1.2.0-unstable-1234567

just remember that the build version is not used in the package version, so this is ok as far as we like to have a single package pushed to myget for every merge we do using the same base semantic version, and I think could be good, so we can for instance merge this at least in dev and forget about it.

> Once everything is merged into develop we can create a release branch where the build number is bumped to 1.2.1 and merge into master and develop.

we can bump the version in dev branch as well, but the question is if we want to bump it soon or later, I mean, take this case as sample "fixing the icon url", if I don't bump the version, myget package `1.4.1-alpha1` will be overwritten (this because myget supports it), so probably best to at least bump the version to `1.4.1-alpha2` as you did, then from there on just pushing merges over it **or** we can re-enable pushing the version on myget using also the build number.

out there they're pushing adding also the build number:

image

I don't know when they bump the version, but probably just after had released the previous pre-release, I mean if they released beta1, they change the version to beta2 before accepting other PR, or in the first PR they bump, or finally they just don't care and remain on beta1 until they declare they want to start naming beta2, in fact using the build number on myget packages you stay in peace.

So what we do? add build number to myget packages? merge bumping the version first time?

**Comment by mauroservienti** [comment]
Let me describe a scenario, let's say that we are working in parallel on one new feature and two bug fixes. So we actually have 3 branches. On develop version is 1.2.3, on each branch we bump the version according to SemVer the result is that on both bug-fix branches we have 1.2.4

Should the rule be that feature branches do not exist and to fix bugs we must use support branches?

**Comment by micdenny** [comment]
The bumping is done when merging, actually you will get a conflict after
the first branch has merged, and you have to merge/rebase the next ones.

The problem is when you don't change the version, so you don't get
conflicts and you merge over the latest develop version, and this time the
build server will push the package on MyGet with the same latest version
(no build version is used) and this could be confusioning, I think that if
we add -build to the develop packages we are good to go.

3 branches in parallel, all the branches can bump or not the version, in
any case a new PR is created to push changes, because they are code changes
every PR has to bump the version. The first goes in, won, other PR now has
to simply rebase (the rebase should be a rule if we want much cleaner
history), the bump the version again, for this reason the bump could be
requested just before merging, the community understand this quickly, and
they create PRs with no bumped version and wait the confirm of the team.

If then you have a change with no relevant code, you can push over the
latest version, a new build package is created, no overwrite is done.

If you accidentally merge a PR without bumbing, no worrie, you're just
pushing a new build version on MyGet, fix on-the-fly the version to the
proper one and commit again.

With this process is difficult to be wrong in master branch, because you
fix everything in develop before, and anyway I have project that pushes
directly on nuget without having MyGet as a rescue and we had really few
problems in the past with wrong commit, in our case we have a step more, so
more robust.



Il martedì 29 dicembre 2015, Mauro Servienti <notifications@github.com> ha
scritto:

> Let me describe a scenario, let's say that we are working in parallel on
> one new feature and two bug fixes. So we actually have 3 branches. On
> develop version is 1.2.3, on each branch we bump the version according to
> SemVer the result is that on both bug-fix branches we have 1.2.4
>
> Should the rule be that feature branches do not exist and to fix bugs we
> must use support branches?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RadicalFx/Radical.Windows.Presentation.CastleWindsor/pull/10#issuecomment-167730139>
> .
>


-- 
Michael Denny
Engage IT Services s.r.l. <http://www.engageitservices.it/>
Software Architect, Trainer and Consultant
Microsoft MVP .NET
<http://mvp.microsoft.com/en-us/mvp/Michael%20Denny-5000735>
More about me <http://about.me/micdenny>

**Comment by mauroservienti** [comment]
I think that we have a valid approach especially since in the package id we have the build number.
I'll bump the version of this since we need to push it, in the end to Nuget.

**Comment by micdenny** [comment]
@mauroservienti so you're going to remove the bumping version commit?

**Comment by mauroservienti** [comment]
No, sorry. This is ready to be merged and then released.

**Comment by micdenny** [comment]
ok I merge then :)

**Comment by mauroservienti** [comment]
fantastic, thanks.

**Pull request merged**
